export const LOAD_TOURS_START = "LOAD_TOURS_START"
export const LOAD_TOURS_SUCCESS = "LOAD_TOURS_SUCCESS"
export const LOAD_TOURS_FAIL = "LOAD_TOURS_FAIL"

export const LOAD_SINGLE_TOUR_START = "LOAD_SINGLE_TOUR_START"
export const LOAD_SINGLE_TOUR_SUCCESS = "LOAD_SINGLE_TOUR_SUCCESS"
export const LOAD_SINGLE_TOUR_FAIL = "LOAD_SINGLE_TOUR_FAIL"
