export const LOAD_TOURS_START = "LOAD_TOURS_START"
export const LOAD_TOURS_SUCCESS = "LOAD_TOURS_SUCCESS"
export const LOAD_TOURS_FAIL = "LOAD_TOURS_FAIL"

export const LOAD_SINGLE_TOUR_START = "LOAD_SINGLE_TOUR_START"
export const LOAD_SINGLE_TOUR_SUCCESS = "LOAD_SINGLE_TOUR_SUCCESS"
export const LOAD_SINGLE_TOUR_FAIL = "LOAD_SINGLE_TOUR_FAIL"

export const AUTH_START = "AUTH_START"
export const AUTH_SUCCESS = "AUTH_SUCCESS"
export const AUTH_FAIL = "AUTH_FAIL"
export const AUTH_LOGOUT = "AUTH_LOGOUT"
export const AUTH_EDIT = "AUTH_EDIT"

export const SUBMIT_REVIEW = "SUBMIT_REVIEW"

export const LOAD_USERS_START = "LOAD_USERS_START"
export const LOAD_USERS_SUCCESS = "LOAD_USERS_SUCCESS"
export const LOAD_USERS_FAIL = "LOAD_USERS_FAIL"

// TODO: actiontypes to add

export const DELETE_USER = "DELETE_USER"
export const EDIT_USER = "EDIT_USER"
export const STATUTE_USER = "STATUTE_USER"

export const ADD_TOUR = "ADD_TOUR"
export const DELETE_TOUR = "DELETE_TOUR"
export const EDIT_TOUR = "EDIT_TOUR"
