export const LOAD_TOURS_START = "LOAD_TOURS_START"
export const LOAD_TOURS_SUCCESS = "LOAD_TOURS_SUCCESS"
export const LOAD_TOURS_FAIL = "LOAD_TOURS_FAIL"

export const LOAD_SINGLE_TOUR_START = "LOAD_SINGLE_TOUR_START"
export const LOAD_SINGLE_TOUR_SUCCESS = "LOAD_SINGLE_TOUR_SUCCESS"
export const LOAD_SINGLE_TOUR_FAIL = "LOAD_SINGLE_TOUR_FAIL"

export const AUTH_START = "AUTH_START"
export const AUTH_SUCCESS = "AUTH_SUCCESS"
export const AUTH_FAIL = "AUTH_FAIL"
export const AUTH_LOGOUT = "AUTH_LOGOUT"
